/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author skzab
 */
public class View extends javax.swing.JFrame {

    /** Creates new form View */
    public View() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTextFieldYUAN = new javax.swing.JTextField();
        jTextFieldUSD = new javax.swing.JTextField();
        jTextFieldGBP = new javax.swing.JTextField();
        jTextFieldEU = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        this.setLocationRelativeTo(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldYUAN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldYUANKeyReleased(evt);
            }
        });

        jTextFieldUSD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldUSDKeyReleased(evt);
            }
        });

        jTextFieldGBP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldGBPKeyReleased(evt);
            }
        });

        jTextFieldEU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldEUKeyReleased(evt);
            }
        });

        jLabel1.setText("EURO");

        jLabel2.setText("USD");

        jLabel3.setText("GBP");

        jLabel4.setText("YUAN");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Currency Converter");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jTextFieldEU, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jTextFieldUSD, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jTextFieldGBP, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel4)
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addComponent(jTextFieldYUAN, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldUSD, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldGBP, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldEU, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldYUAN, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>                        

    MultiCurrencyConverter mmc = new MultiCurrencyConverter();

    private void jTextFieldEUKeyReleased(java.awt.event.KeyEvent evt) {
        double eu = 0;
        try
        {
            eu = Double.parseDouble(jTextFieldEU.getText());
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
        jTextFieldUSD.setText(String.valueOf(String.format("%.2f",mmc.toUSD(eu))));
        jTextFieldGBP.setText(String.valueOf(String.format("%.2f",mmc.toGBP(eu))));
        jTextFieldYUAN.setText(String.valueOf(String.format("%.2f",mmc.toYUAN(eu))));
    }

    private void jTextFieldUSDKeyReleased(java.awt.event.KeyEvent evt) {
        double usd = 0;
        try
        {
            usd = Double.parseDouble(jTextFieldUSD.getText());
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
        double base = mmc.usdToBase(usd);

        jTextFieldEU.setText(String.valueOf(String.format("%.2f",base)));
        jTextFieldGBP.setText(String.valueOf(String.format("%.2f", mmc.toGBP(base))));
        jTextFieldYUAN.setText(String.valueOf(String.format("%.2f", mmc.toYUAN(base))));
    }

    private void jTextFieldGBPKeyReleased(java.awt.event.KeyEvent evt) {
        double gbp = 0;
        try
        {
            gbp = Double.parseDouble(jTextFieldGBP.getText());
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
        double base = mmc.gbpToBase(gbp);

        jTextFieldEU.setText(String.valueOf(String.format("%.2f",base)));
        jTextFieldUSD.setText(String.valueOf(String.format("%.2f", mmc.toUSD(base))));
        jTextFieldYUAN.setText(String.valueOf(String.format("%.2f", mmc.toYUAN(base))));
    }

    private void jTextFieldYUANKeyReleased(java.awt.event.KeyEvent evt) {
        double yuan = 0;
        try
        {
            yuan = Double.parseDouble(jTextFieldYUAN.getText());
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
        double base = mmc.yuanToBase(yuan);

        jTextFieldEU.setText(String.valueOf(String.format("%.2f",base)));
        jTextFieldUSD.setText(String.valueOf(String.format("%.2f", mmc.toUSD(base))));
        jTextFieldGBP.setText(String.valueOf(String.format("%.2f", mmc.toGBP(base))));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextFieldEU;
    private javax.swing.JTextField jTextFieldGBP;
    private javax.swing.JTextField jTextFieldUSD;
    private javax.swing.JTextField jTextFieldYUAN;
    // End of variables declaration                   

}
